import type {
  ChartPoint,
  Customer,
  DashboardMetric,
  Employee,
  Equipment,
  Evaluation,
  Inspection,
  Lead,
  Material,
  Quote,
  ScheduleEvent,
  ServiceOrder,
  ServiceOrderChecklistItem,
  ServiceOrderChecklistPhoto,
  ServiceOrderEmployee,
  ServiceOrderEquipment,
  ServiceOrderMaterial,
  ServiceMaterialRequest,
  ServiceMaterialRequestItem,
  SessionUser,
  SupervisorEvaluation,
  AuditLog,
  ChecklistTemplate,
  ChecklistTemplateItem,
  ServiceOrderChecklistEvent,
  SiteBeforeAfter,
  SiteTestimonial,
} from "./types";

export const users: SessionUser[] = [
  { id: "usr-owner", name: "Dono", email: "dono@empresa.com", role: "OWNER", isActive: true },
  { id: "usr-gerente", name: "Gerente", email: "gerente@empresa.com", role: "GERENTE", isActive: true },
  { id: "usr-supervisor", name: "Carlos Nunes", email: "supervisor@empresa.com", role: "SUPERVISOR_OBRA", isActive: true },
  { id: "usr-supervisor-2", name: "Luciana Freitas", email: "luciana@empresa.com", role: "SUPERVISOR_OBRA", isActive: true },
  { id: "usr-almoxarifado", name: "Paulo Almoxarifado", email: "almoxarifado@empresa.com", role: "ALMOXARIFADO", isActive: true },
  { id: "usr-comercial", name: "Comercial", email: "comercial@empresa.com", role: "COMERCIAL", isActive: true },
  { id: "usr-financeiro", name: "Financeiro", email: "financeiro@empresa.com", role: "FINANCEIRO", isActive: true },
  { id: "usr-colaborador", name: "Joao Pereira", email: "colaborador@empresa.com", role: "COLABORADOR", isActive: true },
  { id: "usr-colaborador-marina", name: "Marina Lopes", email: "marina.login@empresa.com", role: "COLABORADOR", isActive: true },
  { id: "usr-colaborador-rafael", name: "Rafael Costa", email: "rafael.login@empresa.com", role: "COLABORADOR", isActive: true },
  { id: "usr-colaborador-diego", name: "Diego Ramos", email: "diego.login@empresa.com", role: "COLABORADOR", isActive: true },
];

export const customers: Customer[] = [
  {
    id: "cus-aurora",
    name: "Condominio Aurora Jardins",
    phone: "(11) 4002-1188",
    email: "sindico@aurorajardins.com",
    document: "44.112.992/0001-81",
    type: "CONDOMINIUM",
    source: "Indicacao",
    notes: "Hall social em marmore travertino, elevadores espelhados e alto fluxo de moradores.",
    totalValue: 134600,
    lastService: "Polimento de travertino",
  },
  {
    id: "cus-martins",
    name: "Residencia Ana Martins",
    phone: "(21) 98822-1010",
    email: "ana@martins.com",
    document: "311.887.220-02",
    type: "PERSON",
    source: "Instagram",
    notes: "Casa recem-reformada com porcelanato acetinado e rodapes de madeira natural.",
    totalValue: 32600,
    lastService: "Limpeza pos-obra",
  },
  {
    id: "cus-lumen",
    name: "Lumen Arquitetura",
    phone: "(31) 3221-6500",
    email: "projetos@lumen.arq.br",
    document: "19.225.845/0001-04",
    type: "ARCHITECT",
    source: "Parceiro",
    notes: "Escritorio parceiro com obras residenciais de alto padrao e exigencia de acabamento fino.",
    totalValue: 173900,
    lastService: "Impermeabilizacao de limestone",
  },
  {
    id: "cus-vista",
    name: "Vista Engenharia",
    phone: "(41) 3030-7654",
    email: "obras@vista.eng.br",
    document: "08.414.340/0001-20",
    type: "CONSTRUCTION_COMPANY",
    source: "Site",
    notes: "Entrega de apartamentos decorados e areas comuns em condominios novos.",
    totalValue: 214200,
    lastService: "Limpeza fina pos-obra",
  },
  {
    id: "cus-serra",
    name: "Hotel Serra Azul",
    phone: "(48) 3344-2020",
    email: "manutencao@serraazul.com",
    document: "52.777.100/0001-60",
    type: "COMPANY",
    source: "Google",
    notes: "Contrato recorrente com execucao noturna e liberacao por etapas.",
    totalValue: 98400,
    lastService: "Cristalizacao de marmore",
  },
  {
    id: "cus-belvedere",
    name: "Penthouse Belvedere",
    phone: "(11) 97654-2400",
    email: "administracao@belvedere.com",
    document: "228.772.980-09",
    type: "PERSON",
    source: "Arquiteto parceiro",
    notes: "Apartamento de luxo com marmore branco prime e itens importados.",
    totalValue: 68500,
    lastService: "Restauracao de marmore",
  },
  {
    id: "cus-cima",
    name: "Clinica Cima",
    phone: "(21) 3012-9090",
    email: "operacoes@clinicacima.com",
    document: "16.222.440/0001-03",
    type: "COMPANY",
    source: "LinkedIn",
    notes: "Ambiente sensivel, baixa poeira, horarios restritos e area em funcionamento.",
    totalValue: 42700,
    lastService: "Impermeabilizacao tecnica",
  },
];

export const leads: Lead[] = [
  {
    id: "lead-001",
    name: "Shopping Terra Nova",
    phone: "(11) 96666-2030",
    email: "facilities@terranova.com",
    source: "Google Ads",
    status: "QUOTE_SENT",
    estimatedValue: 62000,
    nextFollowUpAt: "2026-07-03",
    notes: "Cliente pediu execucao noturna por setores, sem fechamento da operacao.",
  },
  {
    id: "lead-002",
    name: "Casa Alto Jardim",
    phone: "(11) 95590-3311",
    email: "contato@altojardim.com",
    source: "Instagram",
    status: "INSPECTION_SCHEDULED",
    estimatedValue: 18500,
    nextFollowUpAt: "2026-07-02",
    notes: "Vistoria marcada para avaliar manchas em limestone claro.",
  },
  {
    id: "lead-003",
    name: "Construtora Prisma",
    phone: "(19) 3500-8877",
    email: "suprimentos@prisma.com",
    source: "Indicacao",
    status: "NEGOTIATION",
    estimatedValue: 128000,
    nextFollowUpAt: "2026-07-05",
    notes: "Contrato de limpeza pos-obra para 3 torres, comparando fornecedores.",
  },
  {
    id: "lead-004",
    name: "Clinica Vitae",
    phone: "(21) 3012-9090",
    email: "admin@vitae.com",
    source: "Site",
    status: "CONTACTED",
    estimatedValue: 9700,
    nextFollowUpAt: "2026-07-04",
    notes: "Precisa de isolamento de areas sensiveis e relatorio pos-servico.",
  },
  {
    id: "lead-005",
    name: "Edificio Bela Fonte",
    phone: "(31) 99800-5000",
    email: "zeladoria@belafonte.com",
    source: "Whatsapp",
    status: "NEW",
    estimatedValue: 26800,
    nextFollowUpAt: "2026-07-02",
    notes: "Primeiro contato recebido pela manha, deseja visitar obra entregue.",
  },
  {
    id: "lead-006",
    name: "Residencial Vila Europa",
    phone: "(11) 91111-7330",
    email: "gestao@vilaeuropa.com",
    source: "Indicacao",
    status: "NEW",
    estimatedValue: 41000,
    nextFollowUpAt: "2026-07-02",
    notes: "Hall de entrada com granito preto absoluto opaco e riscos perto dos elevadores.",
  },
];

export const siteBeforeAfters: SiteBeforeAfter[] = [
  {
    id: "ba-marmore-belvedere",
    title: "Mármore branco restaurado",
    serviceType: "Restauração de mármore",
    location: "Setor Bueno, Goiânia",
    beforeImageUrl: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=78",
    afterImageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=82",
    description: "Remoção de opacidade, micro riscos e manchas com polimento técnico e proteção final.",
    isPublished: true,
    createdAt: "2026-07-01T09:00:00",
  },
  {
    id: "ba-pos-obra-jardins",
    title: "Entrega fina pós-obra",
    serviceType: "Limpeza pós-obra",
    location: "Jardim Goiás, Goiânia",
    beforeImageUrl: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=78",
    afterImageUrl: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=82",
    description: "Poeira fina, rejunte, vidros e metais entregues com padrão de vistoria profissional.",
    isPublished: true,
    createdAt: "2026-07-02T09:00:00",
  },
  {
    id: "ba-granito-aurora",
    title: "Granito com brilho recuperado",
    serviceType: "Polimento de granito",
    location: "Condomínio alto padrão",
    beforeImageUrl: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=78",
    afterImageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=82",
    description: "Nivelamento visual, limpeza técnica e acabamento para área de alto tráfego.",
    isPublished: true,
    createdAt: "2026-07-03T09:00:00",
  },
];

export const siteTestimonials: SiteTestimonial[] = [
  {
    id: "test-ana-martins",
    customerName: "Ana Martins",
    roleOrNeighborhood: "Residência no Setor Marista",
    rating: 5,
    quote: "A casa ficou pronta para receber os móveis. A equipe foi cuidadosa, pontual e entregou tudo com muito capricho.",
    serviceType: "Limpeza pós-obra",
    isPublished: true,
    createdAt: "2026-07-01T10:00:00",
  },
  {
    id: "test-aurora",
    customerName: "Síndico Aurora Jardins",
    roleOrNeighborhood: "Condomínio residencial",
    rating: 5,
    quote: "O hall voltou a ter brilho sem parar a rotina dos moradores. A comunicação e o cuidado com a área comum foram excelentes.",
    serviceType: "Polimento de travertino",
    isPublished: true,
    createdAt: "2026-07-02T10:00:00",
  },
  {
    id: "test-lumen",
    customerName: "Lumen Arquitetura",
    roleOrNeighborhood: "Escritório parceiro",
    rating: 5,
    quote: "Indicamos para obras de alto padrão porque entendem acabamento fino e protegem o imóvel antes de executar.",
    serviceType: "Restauração de mármore",
    isPublished: true,
    createdAt: "2026-07-03T10:00:00",
  },
];

export const inspections: Inspection[] = [
  {
    id: "ins-001",
    customerName: "Condominio Aurora Jardins",
    surfaceType: "MARBLE",
    serviceType: "POLISHING",
    areaM2: 420,
    currentState: "Perda de brilho, riscos leves e manchas proximas aos elevadores",
    technicalRisk: "Baixo",
    inspectionDate: "2026-06-27",
  },
  {
    id: "ins-002",
    customerName: "Residencia Ana Martins",
    surfaceType: "PORCELAIN",
    serviceType: "POST_CONSTRUCTION_CLEANING",
    areaM2: 180,
    currentState: "Residuo cimenticio no rejunte e poeira fina em esquadrias",
    technicalRisk: "Medio",
    inspectionDate: "2026-06-29",
  },
  {
    id: "ins-003",
    customerName: "Hotel Serra Azul",
    surfaceType: "MARBLE",
    serviceType: "CRYSTALLIZATION",
    areaM2: 260,
    currentState: "Pontos opacos na recepcao por alto trafego",
    technicalRisk: "Baixo",
    inspectionDate: "2026-06-30",
  },
  {
    id: "ins-004",
    customerName: "Penthouse Belvedere",
    surfaceType: "MARBLE",
    serviceType: "RESTORATION",
    areaM2: 145,
    currentState: "Marmore branco prime com marcas de acido e micro riscos",
    technicalRisk: "Alto",
    inspectionDate: "2026-06-28",
  },
  {
    id: "ins-005",
    customerName: "Vista Engenharia",
    surfaceType: "GRANITE",
    serviceType: "POLISHING",
    areaM2: 310,
    currentState: "Granito com marcas de tinta, rejunte e perda parcial de brilho",
    technicalRisk: "Medio",
    inspectionDate: "2026-07-01",
  },
];

export const quotes: Quote[] = [
  {
    id: "quo-001",
    customerName: "Condominio Aurora Jardins",
    status: "APPROVED",
    validUntil: "2026-07-12",
    subtotal: 48600,
    discount: 1600,
    total: 47000,
    paymentTerms: "40% entrada, 60% na entrega",
  },
  {
    id: "quo-002",
    customerName: "Shopping Terra Nova",
    status: "SENT",
    validUntil: "2026-07-18",
    subtotal: 62000,
    discount: 0,
    total: 62000,
    paymentTerms: "30/40/30 por etapa",
  },
  {
    id: "quo-003",
    customerName: "Residencia Ana Martins",
    status: "APPROVED",
    validUntil: "2026-07-09",
    subtotal: 12600,
    discount: 400,
    total: 12200,
    paymentTerms: "50% entrada, 50% conclusao",
  },
  {
    id: "quo-004",
    customerName: "Hotel Serra Azul",
    status: "APPROVED",
    validUntil: "2026-07-08",
    subtotal: 38400,
    discount: 0,
    total: 38400,
    paymentTerms: "Boleto 7 dias apos entrega",
  },
  {
    id: "quo-005",
    customerName: "Vista Engenharia",
    status: "SENT",
    validUntil: "2026-07-14",
    subtotal: 52800,
    discount: 2800,
    total: 50000,
    paymentTerms: "30% entrada, 40% medicao, 30% entrega",
  },
  {
    id: "quo-006",
    customerName: "Lumen Arquitetura",
    status: "DRAFT",
    validUntil: "2026-07-11",
    subtotal: 28600,
    discount: 900,
    total: 27700,
    paymentTerms: "50% entrada, 50% entrega",
  },
  {
    id: "quo-007",
    customerName: "Penthouse Belvedere",
    status: "APPROVED",
    validUntil: "2026-07-15",
    subtotal: 68500,
    discount: 2500,
    total: 66000,
    paymentTerms: "Entrada + saldo na vistoria de aceite",
  },
];

export const employees: Employee[] = [
  {
    id: "emp-joao",
    userId: "usr-colaborador",
    name: "Joao Pereira",
    phone: "(11) 97777-4545",
    email: "joao@empresa.com",
    document: "120.445.882-00",
    roleName: "Polidor senior",
    specialty: "Polimento e cristalizacao",
    status: "ACTIVE",
    dailyCost: 320,
    hiredAt: "2022-03-11",
    notes: "Referencia em acabamento fino, bordas e espelhamento de marmore.",
    averageRating: 4.9,
    serviceOrdersCount: 42,
    lastJob: "Hotel Serra Azul",
    lastEvaluationAt: "2026-06-26",
    needsTraining: false,
    criteriaAverages: { punctuality: 5, quality: 4.9, productivity: 4.7, care: 5, teamwork: 4.9, clientPosture: 5, checklistCompliance: 4.8 },
    strengths: ["Acabamento premium", "Postura com cliente", "Organizacao de area"],
    improvements: ["Registrar mais fotos intermediarias"],
  },
  {
    id: "emp-marina",
    userId: "usr-colaborador-marina",
    name: "Marina Lopes",
    phone: "(11) 98888-1012",
    email: "marina@empresa.com",
    document: "299.332.441-22",
    roleName: "Tecnica de limpeza",
    specialty: "Limpeza pos-obra",
    status: "ACTIVE",
    dailyCost: 260,
    hiredAt: "2023-01-18",
    notes: "Muito forte em organizacao de checklist, acabamento final e relacionamento com moradores.",
    averageRating: 4.7,
    serviceOrdersCount: 29,
    lastJob: "Hotel Serra Azul",
    lastEvaluationAt: "2026-06-26",
    needsTraining: false,
    criteriaAverages: { punctuality: 4.9, quality: 4.5, productivity: 4.8, care: 4.9, teamwork: 4.8, clientPosture: 4.6, checklistCompliance: 5 },
    strengths: ["Checklist", "Produtividade", "Cuidado com mobiliario"],
    improvements: ["Aprofundar remocao de manchas em cantos"],
  },
  {
    id: "emp-carlos",
    userId: "usr-supervisor",
    name: "Carlos Nunes",
    phone: "(11) 95555-0988",
    email: "carlos@empresa.com",
    document: "400.990.112-70",
    roleName: "Supervisor de campo",
    specialty: "Lideranca de obra",
    status: "ACTIVE",
    dailyCost: 380,
    hiredAt: "2021-09-02",
    notes: "Lidera equipes grandes, turnos noturnos e entregas para condominios exigentes.",
    averageRating: 4.9,
    serviceOrdersCount: 58,
    lastJob: "Penthouse Belvedere",
    lastEvaluationAt: "2026-06-26",
    needsTraining: false,
    criteriaAverages: { punctuality: 5, quality: 4.8, productivity: 4.8, care: 4.9, teamwork: 5, clientPosture: 4.9, checklistCompliance: 4.9 },
    strengths: ["Lideranca", "Planejamento", "Relatorio tecnico"],
    improvements: ["Delegar fotos de detalhe para reduzir gargalo"],
  },
  {
    id: "emp-rafael",
    userId: "usr-colaborador-rafael",
    name: "Rafael Costa",
    phone: "(11) 94412-8001",
    email: "rafael@empresa.com",
    document: "219.092.441-55",
    roleName: "Especialista em granito",
    specialty: "Polimento de granito",
    status: "ACTIVE",
    dailyCost: 310,
    hiredAt: "2022-11-07",
    notes: "Especialista em granito escuro, acabamento uniforme e recuperacao de brilho.",
    averageRating: 4.8,
    serviceOrdersCount: 34,
    lastJob: "Vista Engenharia",
    lastEvaluationAt: "2026-06-30",
    needsTraining: false,
    criteriaAverages: { punctuality: 4.8, quality: 4.9, productivity: 4.7, care: 4.8, teamwork: 4.7, clientPosture: 4.8, checklistCompliance: 4.8 },
    strengths: ["Granito escuro", "Regularidade", "Baixo retrabalho"],
    improvements: ["Antecipar lista de insumos antes da obra"],
  },
  {
    id: "emp-bianca",
    name: "Bianca Alves",
    phone: "(21) 94444-7676",
    email: "bianca@empresa.com",
    document: "700.331.542-80",
    roleName: "Aplicadora tecnica",
    specialty: "Impermeabilizacao",
    status: "ON_LEAVE",
    dailyCost: 300,
    hiredAt: "2024-04-20",
    notes: "Retorno previsto para agosto. Forte em protecao de area e aplicacao controlada.",
    averageRating: 4.4,
    serviceOrdersCount: 16,
    lastJob: "Lumen Arquitetura",
    lastEvaluationAt: "2026-05-21",
    needsTraining: false,
    criteriaAverages: { punctuality: 4.5, quality: 4.6, productivity: 4.1, care: 4.8, teamwork: 4.4, clientPosture: 4.2, checklistCompliance: 4.4 },
    strengths: ["Precisao", "Protecao de area", "Aplicacao uniforme"],
    improvements: ["Ritmo em areas extensas", "Comunicar prazo de cura com mais clareza"],
  },
  {
    id: "emp-ines",
    name: "Ines Carvalho",
    phone: "(31) 98877-4410",
    email: "ines@empresa.com",
    document: "812.440.190-61",
    roleName: "Auxiliar lider",
    specialty: "Limpeza fina e protecao",
    status: "ACTIVE",
    dailyCost: 240,
    hiredAt: "2023-08-14",
    notes: "Boa disciplina de obra, precisa ganhar velocidade em ambientes grandes.",
    averageRating: 4.2,
    serviceOrdersCount: 18,
    lastJob: "Vista Engenharia",
    lastEvaluationAt: "2026-05-18",
    needsTraining: true,
    trainingAlert: "Sem avaliacao recente e produtividade abaixo da media da equipe.",
    criteriaAverages: { punctuality: 4.6, quality: 4.2, productivity: 3.8, care: 4.5, teamwork: 4.3, clientPosture: 4.1, checklistCompliance: 4.2 },
    strengths: ["Capricho", "Cuidado com protecoes", "Disciplina"],
    improvements: ["Produtividade", "Autonomia no checklist", "Priorizar areas criticas"],
  },
  {
    id: "emp-diego",
    userId: "usr-colaborador-diego",
    name: "Diego Ramos",
    phone: "(11) 93330-2020",
    email: "diego@empresa.com",
    document: "501.778.110-94",
    roleName: "Auxiliar de polimento",
    specialty: "Apoio de restauracao",
    status: "ACTIVE",
    dailyCost: 220,
    hiredAt: "2025-02-03",
    notes: "Bom potencial, mas precisa reforcar pontualidade, postura e checklist.",
    averageRating: 3.4,
    serviceOrdersCount: 9,
    lastJob: "Penthouse Belvedere",
    lastEvaluationAt: "2026-06-12",
    needsTraining: true,
    trainingAlert: "Treinamento recomendado em checklist, comunicacao com cliente e preparacao de area.",
    criteriaAverages: { punctuality: 3.2, quality: 3.7, productivity: 3.5, care: 3.9, teamwork: 3.6, clientPosture: 3.1, checklistCompliance: 3.0 },
    strengths: ["Aprende rapido", "Boa execucao quando acompanhado"],
    improvements: ["Pontualidade", "Checklist", "Postura com cliente"],
  },
  {
    id: "emp-luciana",
    userId: "usr-supervisor-2",
    name: "Luciana Freitas",
    phone: "(11) 97720-9922",
    email: "luciana@empresa.com",
    document: "233.871.900-44",
    roleName: "Supervisora de obra",
    specialty: "Limpeza pos-obra e impermeabilizacao",
    status: "ACTIVE",
    dailyCost: 360,
    hiredAt: "2022-06-09",
    notes: "Supervisora com forte controle de checklist, materiais e relacionamento com arquitetos.",
    averageRating: 4.7,
    supervisorAverageRating: 4.8,
    serviceOrdersCount: 37,
    lastJob: "Residencia Ana Martins",
    lastEvaluationAt: "2026-06-29",
    needsTraining: false,
    criteriaAverages: { punctuality: 4.8, quality: 4.7, productivity: 4.5, care: 4.9, teamwork: 4.8, clientPosture: 4.9, checklistCompliance: 4.7 },
    strengths: ["Organizacao", "Comunicacao", "Controle de evidencias"],
    improvements: ["Antecipar devolucao de equipamentos"],
  },
  {
    id: "emp-paulo",
    userId: "usr-almoxarifado",
    name: "Paulo Henrique",
    phone: "(11) 95590-7000",
    email: "almoxarifado@empresa.com",
    document: "100.204.309-08",
    roleName: "Responsavel de almoxarifado",
    specialty: "Materiais e equipamentos",
    status: "ACTIVE",
    dailyCost: 280,
    hiredAt: "2023-04-04",
    notes: "Controla separacao, entrega, retorno e baixa de produtos e maquinas.",
    averageRating: 4.5,
    serviceOrdersCount: 21,
    lastJob: "Preparacao OS-2406",
    lastEvaluationAt: "2026-06-28",
    needsTraining: false,
    criteriaAverages: { punctuality: 4.6, quality: 4.5, productivity: 4.6, care: 4.7, teamwork: 4.5, clientPosture: 4.3, checklistCompliance: 4.6 },
    strengths: ["Estoque minimo", "Separacao rapida", "Controle de retorno"],
    improvements: ["Padronizar fotos de equipamentos danificados"],
  },
];

export const serviceOrders: ServiceOrder[] = [
  {
    id: "os-2401",
    customerId: "cus-aurora",
    customerName: "Condominio Aurora Jardins",
    quoteId: "quo-001",
    title: "Polimento e cristalizacao do hall social",
    serviceType: "POLISHING",
    description: "Recuperacao de brilho, remocao de riscos leves e cristalizacao final em marmore travertino.",
    address: "Av. das Nacoes, 1200 - Sao Paulo, SP",
    scheduledStart: "2026-07-02T08:00:00",
    scheduledEnd: "2026-07-05T18:00:00",
    status: "IN_PROGRESS",
    supervisorEmployeeId: "emp-carlos",
    supervisorUserId: "usr-supervisor",
    assignedByUserId: "usr-gerente",
    assignedAt: "2026-07-01T14:00:00",
    internalNotes: "Isolar elevadores, trabalhar por blocos e validar brilho antes de liberar cada setor.",
    clientNotes: "Execucao permitida das 8h as 18h, sem bloquear os dois elevadores ao mesmo tempo.",
    employeeIds: ["emp-joao", "emp-carlos", "emp-ines"],
    tasks: [
      { id: "task-1", title: "Isolamento das areas e protecao de rodapes", done: true },
      { id: "task-2", title: "Desbaste tecnico e nivelamento de riscos", done: true },
      { id: "task-3", title: "Polimento progressivo", done: false },
      { id: "task-4", title: "Cristalizacao final e fotos de entrega", done: false },
    ],
    revenue: 47000,
    expenses: 18300,
  },
  {
    id: "os-2402",
    customerId: "cus-martins",
    customerName: "Residencia Ana Martins",
    quoteId: "quo-003",
    title: "Limpeza pos-obra de porcelanato",
    serviceType: "POST_CONSTRUCTION_CLEANING",
    description: "Remocao de residuos cimenticios, limpeza de rejunte, esquadrias e acabamento final.",
    address: "Rua das Jabuticabeiras, 88 - Rio de Janeiro, RJ",
    scheduledStart: "2026-07-04T09:00:00",
    scheduledEnd: "2026-07-04T17:00:00",
    status: "SCHEDULED",
    supervisorEmployeeId: "emp-luciana",
    supervisorUserId: "usr-supervisor-2",
    assignedByUserId: "usr-gerente",
    assignedAt: "2026-07-01T10:00:00",
    internalNotes: "Usar produto neutro em area gourmet e testar removedor atras da ilha.",
    clientNotes: "Cliente solicitou protecao no rodape de madeira e cuidado com luminarias novas.",
    employeeIds: ["emp-marina", "emp-ines"],
    tasks: [
      { id: "task-5", title: "Teste de produto em area escondida", done: false },
      { id: "task-6", title: "Limpeza mecanizada do porcelanato", done: false },
      { id: "task-7", title: "Limpeza fina de esquadrias", done: false },
      { id: "task-8", title: "Fotos de entrega", done: false },
    ],
    revenue: 12200,
    expenses: 4100,
  },
  {
    id: "os-2403",
    customerId: "cus-serra",
    customerName: "Hotel Serra Azul",
    quoteId: "quo-004",
    title: "Cristalizacao de marmore em recepcao",
    serviceType: "CRYSTALLIZATION",
    description: "Servico executado em janela noturna com liberacao gradual da recepcao do hotel.",
    address: "Av. Atlantica, 900 - Florianopolis, SC",
    scheduledStart: "2026-06-25T22:00:00",
    scheduledEnd: "2026-06-26T06:00:00",
    status: "DONE",
    supervisorEmployeeId: "emp-carlos",
    supervisorUserId: "usr-supervisor",
    assignedByUserId: "usr-owner",
    assignedAt: "2026-06-24T11:00:00",
    internalNotes: "Obra entregue, avaliacao completa registrada pela supervisao.",
    clientNotes: "Recepcao liberada as 6h com fotos antes/depois enviadas ao cliente.",
    employeeIds: ["emp-joao", "emp-marina", "emp-carlos"],
    tasks: [
      { id: "task-9", title: "Protecao do balcao e comunicacao visual", done: true },
      { id: "task-10", title: "Cristalizacao em duas etapas", done: true },
      { id: "task-11", title: "Limpeza fina e retirada de protecoes", done: true },
      { id: "task-12", title: "Relatorio fotografico", done: true },
    ],
    revenue: 38400,
    expenses: 13200,
  },
  {
    id: "os-2404",
    customerId: "cus-belvedere",
    customerName: "Penthouse Belvedere",
    quoteId: "quo-007",
    title: "Restauracao de marmore branco prime",
    serviceType: "RESTORATION",
    description: "Tratamento de marcas de acido, micro riscos e recuperacao de brilho em apartamento de alto padrao.",
    address: "Rua Haddock Lobo, 1420 - Sao Paulo, SP",
    scheduledStart: "2026-06-30T08:00:00",
    scheduledEnd: "2026-07-01T18:00:00",
    status: "IN_PROGRESS",
    supervisorEmployeeId: "emp-carlos",
    supervisorUserId: "usr-supervisor",
    assignedByUserId: "usr-owner",
    assignedAt: "2026-06-29T16:00:00",
    internalNotes: "Obra atrasada por restricao de elevador. Reforcar equipe para finalizar a cristalizacao.",
    clientNotes: "Morador exige acompanhamento diario e fotos detalhadas de cada ambiente.",
    employeeIds: ["emp-carlos", "emp-diego", "emp-joao"],
    tasks: [
      { id: "task-13", title: "Mapeamento de manchas e teste tecnico", done: true },
      { id: "task-14", title: "Protecao de metais, marcenaria e rodapes", done: true },
      { id: "task-15", title: "Restauracao localizada das marcas de acido", done: true },
      { id: "task-16", title: "Cristalizacao e aceite final", done: false },
    ],
    revenue: 66000,
    expenses: 25800,
  },
  {
    id: "os-2405",
    customerId: "cus-vista",
    customerName: "Vista Engenharia",
    quoteId: "quo-005",
    title: "Polimento de granito em area comum",
    serviceType: "POLISHING",
    description: "Polimento de granito preto absoluto em lobby, circulacao e area de acesso dos decorados.",
    address: "Rua Chile, 880 - Curitiba, PR",
    scheduledStart: "2026-06-28T07:00:00",
    scheduledEnd: "2026-06-29T19:00:00",
    status: "DONE",
    supervisorEmployeeId: "emp-luciana",
    supervisorUserId: "usr-supervisor-2",
    assignedByUserId: "usr-gerente",
    assignedAt: "2026-06-27T15:00:00",
    internalNotes: "Entrega concluida; falta avaliacao da equipe para fechar a OS.",
    clientNotes: "Construtora pediu relatorio com antes/depois para anexar ao termo de entrega.",
    employeeIds: ["emp-rafael", "emp-ines", "emp-diego"],
    tasks: [
      { id: "task-17", title: "Remocao de respingos de tinta", done: true },
      { id: "task-18", title: "Polimento de granito preto", done: true },
      { id: "task-19", title: "Lavagem final e selagem", done: true },
      { id: "task-20", title: "Fotos e relatorio para construtora", done: true },
    ],
    revenue: 50000,
    expenses: 19400,
  },
  {
    id: "os-2406",
    customerId: "cus-lumen",
    customerName: "Lumen Arquitetura",
    quoteId: "quo-006",
    title: "Impermeabilizacao de limestone",
    serviceType: "WATERPROOFING",
    description: "Impermeabilizacao de pedra natural em lavabo e varanda gourmet de projeto residencial.",
    address: "Rua Grao Mogol, 520 - Belo Horizonte, MG",
    scheduledStart: "2026-07-07T08:00:00",
    scheduledEnd: "2026-07-08T16:00:00",
    status: "PREPARING",
    supervisorEmployeeId: "emp-luciana",
    supervisorUserId: "usr-supervisor-2",
    assignedByUserId: "usr-gerente",
    assignedAt: "2026-07-01T17:00:00",
    internalNotes: "Separar selador premium, manta de protecao e teste de absorcao antes da aplicacao.",
    clientNotes: "Arquiteta solicitou cuidado com esquadrias importadas e prazo de cura claro.",
    employeeIds: ["emp-bianca", "emp-marina"],
    tasks: [
      { id: "task-21", title: "Checklist de materiais e EPIs", done: true },
      { id: "task-22", title: "Teste de absorcao", done: false },
      { id: "task-23", title: "Aplicacao do impermeabilizante", done: false },
      { id: "task-24", title: "Orientacoes de cura e garantia", done: false },
    ],
    revenue: 27700,
    expenses: 9700,
  },
];

export const serviceOrderEmployees: ServiceOrderEmployee[] = [
  { id: "soe-2401-carlos", serviceOrderId: "os-2401", employeeId: "emp-carlos", roleInService: "SUPERVISOR", assignedByUserId: "usr-gerente", assignedAt: "2026-07-01T14:00:00", createdAt: "2026-07-01T14:00:00", updatedAt: "2026-07-01T14:00:00" },
  { id: "soe-2401-joao", serviceOrderId: "os-2401", employeeId: "emp-joao", roleInService: "POLIDOR", assignedByUserId: "usr-gerente", assignedAt: "2026-07-01T14:00:00", createdAt: "2026-07-01T14:00:00", updatedAt: "2026-07-01T14:00:00" },
  { id: "soe-2401-ines", serviceOrderId: "os-2401", employeeId: "emp-ines", roleInService: "AUXILIAR", assignedByUserId: "usr-gerente", assignedAt: "2026-07-01T14:00:00", createdAt: "2026-07-01T14:00:00", updatedAt: "2026-07-01T14:00:00" },
  { id: "soe-2402-luciana", serviceOrderId: "os-2402", employeeId: "emp-luciana", roleInService: "SUPERVISOR", assignedByUserId: "usr-gerente", assignedAt: "2026-07-01T10:00:00", createdAt: "2026-07-01T10:00:00", updatedAt: "2026-07-01T10:00:00" },
  { id: "soe-2402-marina", serviceOrderId: "os-2402", employeeId: "emp-marina", roleInService: "TECNICO", assignedByUserId: "usr-gerente", assignedAt: "2026-07-01T10:00:00", createdAt: "2026-07-01T10:00:00", updatedAt: "2026-07-01T10:00:00" },
  { id: "soe-2402-ines", serviceOrderId: "os-2402", employeeId: "emp-ines", roleInService: "AUXILIAR", assignedByUserId: "usr-gerente", assignedAt: "2026-07-01T10:00:00", createdAt: "2026-07-01T10:00:00", updatedAt: "2026-07-01T10:00:00" },
  { id: "soe-2404-carlos", serviceOrderId: "os-2404", employeeId: "emp-carlos", roleInService: "SUPERVISOR", assignedByUserId: "usr-owner", assignedAt: "2026-06-29T16:00:00", createdAt: "2026-06-29T16:00:00", updatedAt: "2026-06-29T16:00:00" },
  { id: "soe-2404-diego", serviceOrderId: "os-2404", employeeId: "emp-diego", roleInService: "AUXILIAR", assignedByUserId: "usr-owner", assignedAt: "2026-06-29T16:00:00", createdAt: "2026-06-29T16:00:00", updatedAt: "2026-06-29T16:00:00" },
  { id: "soe-2404-joao", serviceOrderId: "os-2404", employeeId: "emp-joao", roleInService: "POLIDOR", assignedByUserId: "usr-owner", assignedAt: "2026-06-29T16:00:00", createdAt: "2026-06-29T16:00:00", updatedAt: "2026-06-29T16:00:00" },
  { id: "soe-2406-luciana", serviceOrderId: "os-2406", employeeId: "emp-luciana", roleInService: "SUPERVISOR", assignedByUserId: "usr-gerente", assignedAt: "2026-07-01T17:00:00", createdAt: "2026-07-01T17:00:00", updatedAt: "2026-07-01T17:00:00" },
  { id: "soe-2406-bianca", serviceOrderId: "os-2406", employeeId: "emp-bianca", roleInService: "TECNICO", assignedByUserId: "usr-gerente", assignedAt: "2026-07-01T17:00:00", createdAt: "2026-07-01T17:00:00", updatedAt: "2026-07-01T17:00:00" },
  { id: "soe-2406-marina", serviceOrderId: "os-2406", employeeId: "emp-marina", roleInService: "AUXILIAR", assignedByUserId: "usr-gerente", assignedAt: "2026-07-01T17:00:00", createdAt: "2026-07-01T17:00:00", updatedAt: "2026-07-01T17:00:00" },
];

export const serviceOrderChecklistItems: ServiceOrderChecklistItem[] = [
  { id: "chk-2401-1", serviceOrderId: "os-2401", title: "Isolamento e protecao", description: "Proteger rodapes, elevadores e areas de circulacao.", sortOrder: 1, status: "DONE", isRequired: true, requiresPhoto: true, minimumPhotos: 1, assignedEmployeeId: "emp-ines", completedByEmployeeId: "emp-ines", startedByUserId: "usr-supervisor", completedByUserId: "usr-supervisor", validatedByUserId: "usr-supervisor", startedAt: "2026-07-02T08:30:00", completedAt: "2026-07-02T09:10:00", validatedAt: "2026-07-02T09:20:00", completionNotes: "Protecao completa validada com fotos.", notes: "Protecao completa validada com fotos.", createdByUserId: "usr-gerente", plannedStartAt: "2026-07-02T08:00:00", dueAt: "2026-07-02T10:00:00", createdAt: "2026-07-01T14:10:00", updatedAt: "2026-07-02T09:20:00" },
  { id: "chk-2401-2", serviceOrderId: "os-2401", title: "Desbaste tecnico", description: "Remover riscos leves e nivelar brilho inicial.", sortOrder: 2, status: "DONE", isRequired: true, requiresPhoto: false, minimumPhotos: 0, assignedEmployeeId: "emp-joao", completedByEmployeeId: "emp-joao", startedByUserId: "usr-supervisor", completedByUserId: "usr-supervisor", validatedByUserId: "usr-supervisor", startedAt: "2026-07-02T10:10:00", completedAt: "2026-07-02T13:30:00", validatedAt: "2026-07-02T13:50:00", completionNotes: "Desbaste sem intercorrencias.", notes: "Desbaste sem intercorrencias.", createdByUserId: "usr-gerente", plannedStartAt: "2026-07-02T10:00:00", dueAt: "2026-07-02T14:00:00", allowCollaboratorAction: true, createdAt: "2026-07-01T14:10:00", updatedAt: "2026-07-02T13:50:00" },
  { id: "chk-2401-3", serviceOrderId: "os-2401", title: "Polimento progressivo", description: "Aplicar sequencia de abrasivos ate acabamento uniforme.", sortOrder: 3, status: "IN_PROGRESS", isRequired: true, requiresPhoto: true, minimumPhotos: 2, assignedEmployeeId: "emp-joao", startedByUserId: "usr-supervisor", startedAt: "2026-07-02T15:00:00", createdByUserId: "usr-gerente", plannedStartAt: "2026-07-02T14:00:00", dueAt: "2026-07-03T12:00:00", allowCollaboratorAction: true, createdAt: "2026-07-01T14:10:00", updatedAt: "2026-07-02T15:00:00" },
  { id: "chk-2401-4", serviceOrderId: "os-2401", title: "Fotos finais e aceite", description: "Registrar fotos antes/depois e colher aceite do cliente.", sortOrder: 4, status: "PENDING", isRequired: true, requiresPhoto: true, minimumPhotos: 2, assignedEmployeeId: "emp-carlos", createdByUserId: "usr-gerente", plannedStartAt: "2026-07-05T15:00:00", dueAt: "2026-07-05T18:00:00", createdAt: "2026-07-01T14:10:00", updatedAt: "2026-07-01T14:10:00" },
  { id: "chk-2402-1", serviceOrderId: "os-2402", title: "Conferir estado inicial do imovel", description: "Validar ambientes, proteger itens sensiveis e registrar condicoes antes da limpeza.", sortOrder: 1, status: "PENDING", isRequired: true, requiresPhoto: true, minimumPhotos: 2, assignedEmployeeId: "emp-marina", createdByUserId: "usr-gerente", plannedStartAt: "2026-07-04T08:00:00", dueAt: "2026-07-04T09:30:00", createdAt: "2026-07-01T10:10:00", updatedAt: "2026-07-01T10:10:00" },
  { id: "chk-2402-2", serviceOrderId: "os-2402", title: "Remover residuos grossos", description: "Recolher sobras de obra, plastico, massa e poeira pesada antes da limpeza fina.", sortOrder: 2, status: "PENDING", isRequired: true, requiresPhoto: false, minimumPhotos: 0, assignedEmployeeId: "emp-ines", createdByUserId: "usr-gerente", plannedStartAt: "2026-07-04T09:30:00", dueAt: "2026-07-04T12:00:00", allowCollaboratorAction: true, createdAt: "2026-07-01T10:10:00", updatedAt: "2026-07-01T10:10:00" },
  { id: "chk-2404-1", serviceOrderId: "os-2404", title: "Protecao de mobiliario", description: "Proteger marcenaria, metais e rodapes importados.", sortOrder: 1, status: "DONE", isRequired: true, requiresPhoto: true, minimumPhotos: 1, assignedEmployeeId: "emp-diego", completedByEmployeeId: "emp-diego", startedByUserId: "usr-supervisor", completedByUserId: "usr-supervisor", validatedByUserId: "usr-supervisor", startedAt: "2026-06-30T08:40:00", completedAt: "2026-06-30T09:20:00", validatedAt: "2026-06-30T09:35:00", completionNotes: "Fotos anexadas.", notes: "Fotos anexadas.", createdByUserId: "usr-owner", plannedStartAt: "2026-06-30T08:00:00", dueAt: "2026-06-30T10:00:00", createdAt: "2026-06-29T16:10:00", updatedAt: "2026-06-30T09:35:00" },
  { id: "chk-2404-2", serviceOrderId: "os-2404", title: "Cristalizacao final", description: "Finalizar brilho e registrar aceite do morador.", sortOrder: 2, status: "BLOCKED", isRequired: true, requiresPhoto: true, minimumPhotos: 1, assignedEmployeeId: "emp-joao", blockedReason: "Bloqueado por restricao de elevador e falta de janela para maquina.", problemDescription: "Elevador social reservado pelo condominio.", notes: "Bloqueado por restricao de elevador.", createdByUserId: "usr-owner", plannedStartAt: "2026-07-02T09:00:00", dueAt: "2026-07-02T14:00:00", createdAt: "2026-06-29T16:10:00", updatedAt: "2026-07-02T10:00:00" },
  { id: "chk-2405-1", serviceOrderId: "os-2405", title: "Lixamento intermediario", description: "Corrigir riscos no granito apos teste localizado.", sortOrder: 1, status: "REOPENED", isRequired: true, requiresPhoto: true, minimumPhotos: 1, assignedEmployeeId: "emp-rafael", completedByEmployeeId: "emp-rafael", completedByUserId: "usr-supervisor-2", completedAt: "2026-06-30T11:00:00", problemDescription: "Foto final insuficiente para validar acabamento.", notes: "Reaberto para nova evidencia.", createdByUserId: "usr-gerente", plannedStartAt: "2026-06-30T08:00:00", dueAt: "2026-06-30T12:00:00", allowCollaboratorAction: true, createdAt: "2026-06-29T10:10:00", updatedAt: "2026-06-30T13:00:00" },
  { id: "chk-2406-1", serviceOrderId: "os-2406", title: "Separacao de impermeabilizante", description: "Conferir selador, manta e EPI antes de sair.", sortOrder: 1, status: "PENDING", isRequired: true, requiresPhoto: false, minimumPhotos: 0, assignedEmployeeId: "emp-bianca", createdByUserId: "usr-gerente", plannedStartAt: "2026-07-07T07:30:00", dueAt: "2026-07-07T08:30:00", createdAt: "2026-07-01T17:10:00", updatedAt: "2026-07-01T17:10:00" },
];

export const serviceOrderChecklistPhotos: ServiceOrderChecklistPhoto[] = [
  { id: "chk-photo-1", checklistItemId: "chk-2401-1", serviceOrderId: "os-2401", uploadedByUserId: "usr-supervisor", employeeId: "emp-ines", type: "EVIDENCE", url: "/demo/os-2401-protecao.jpg", fileName: "os-2401-protecao.jpg", mimeType: "image/jpeg", sizeBytes: 284000, caption: "Protecao dos elevadores concluida", createdAt: "2026-07-02T09:08:00" },
  { id: "chk-photo-2", checklistItemId: "chk-2404-1", serviceOrderId: "os-2404", uploadedByUserId: "usr-supervisor", employeeId: "emp-diego", type: "BEFORE", url: "/demo/os-2404-protecao.jpg", fileName: "os-2404-protecao.jpg", mimeType: "image/jpeg", sizeBytes: 312000, caption: "Marcenaria isolada antes do tratamento", createdAt: "2026-06-30T09:18:00" },
  { id: "chk-photo-3", checklistItemId: "chk-2405-1", serviceOrderId: "os-2405", uploadedByUserId: "usr-supervisor-2", employeeId: "emp-rafael", type: "PROBLEM", url: "/demo/os-2405-foto-insuficiente.webp", fileName: "os-2405-foto-insuficiente.webp", mimeType: "image/webp", sizeBytes: 198000, caption: "Foto sem detalhe suficiente do acabamento", createdAt: "2026-06-30T11:02:00" },
];

export const serviceOrderChecklistEvents: ServiceOrderChecklistEvent[] = [
  { id: "chk-event-1", checklistItemId: "chk-2401-1", serviceOrderId: "os-2401", userId: "usr-gerente", employeeId: "emp-ines", type: "ASSIGNED", message: "Ines atribuida ao isolamento e protecao.", newStatus: "PENDING", createdAt: "2026-07-01T14:20:00" },
  { id: "chk-event-2", checklistItemId: "chk-2401-1", serviceOrderId: "os-2401", userId: "usr-supervisor", employeeId: "emp-ines", type: "COMPLETED", message: "Item concluido com foto obrigatoria.", previousStatus: "IN_PROGRESS", newStatus: "DONE", createdAt: "2026-07-02T09:10:00" },
  { id: "chk-event-3", checklistItemId: "chk-2401-1", serviceOrderId: "os-2401", userId: "usr-supervisor", employeeId: "emp-ines", type: "VALIDATED", message: "Supervisor validou a protecao.", previousStatus: "DONE", newStatus: "DONE", createdAt: "2026-07-02T09:20:00" },
  { id: "chk-event-4", checklistItemId: "chk-2404-2", serviceOrderId: "os-2404", userId: "usr-supervisor", employeeId: "emp-joao", type: "BLOCKED", message: "Elevador indisponivel para equipamento.", previousStatus: "PENDING", newStatus: "BLOCKED", createdAt: "2026-07-02T10:00:00" },
  { id: "chk-event-5", checklistItemId: "chk-2405-1", serviceOrderId: "os-2405", userId: "usr-supervisor-2", employeeId: "emp-rafael", type: "REOPENED", message: "Foto insuficiente para validar acabamento.", previousStatus: "DONE", newStatus: "REOPENED", createdAt: "2026-06-30T13:00:00" },
];

export const checklistTemplates: ChecklistTemplate[] = [
  { id: "tpl-pos-obra", name: "Limpeza pos-obra", description: "Fluxo completo para limpeza fina e entrega de imovel apos obra.", serviceType: "POST_CONSTRUCTION_CLEANING", isActive: true, createdByUserId: "usr-owner", createdAt: "2026-06-20T08:00:00", updatedAt: "2026-06-20T08:00:00" },
  { id: "tpl-marmore", name: "Restauracao de marmore", description: "Checklist tecnico para restauracao, polimento e protecao de marmores.", serviceType: "RESTORATION", isActive: true, createdByUserId: "usr-owner", createdAt: "2026-06-20T08:00:00", updatedAt: "2026-06-20T08:00:00" },
  { id: "tpl-granito", name: "Polimento de granito", description: "Etapas de teste, lixamento, acabamento e evidencia fotografica.", serviceType: "POLISHING", isActive: true, createdByUserId: "usr-gerente", createdAt: "2026-06-21T08:00:00", updatedAt: "2026-06-21T08:00:00" },
  { id: "tpl-impermeabilizacao", name: "Impermeabilizacao", description: "Preparacao, aplicacao e validacao de impermeabilizantes.", serviceType: "WATERPROOFING", isActive: true, createdByUserId: "usr-gerente", createdAt: "2026-06-22T08:00:00", updatedAt: "2026-06-22T08:00:00" },
  { id: "tpl-manchas", name: "Remocao de manchas", description: "Diagnostico, teste localizado e remocao controlada.", serviceType: "STAIN_REMOVAL", isActive: true, createdByUserId: "usr-gerente", createdAt: "2026-06-22T08:00:00", updatedAt: "2026-06-22T08:00:00" },
  { id: "tpl-porcelanato", name: "Tratamento de porcelanato", description: "Limpeza, rejunte, acabamento e orientacao de conservacao.", serviceType: "GROUT_CLEANING", isActive: true, createdByUserId: "usr-gerente", createdAt: "2026-06-22T08:00:00", updatedAt: "2026-06-22T08:00:00" },
];

export const checklistTemplateItems: ChecklistTemplateItem[] = [
  { id: "tpl-pos-obra-1", templateId: "tpl-pos-obra", title: "Conferir estado inicial do imovel", description: "Validar ambientes e riscos antes de iniciar.", sortOrder: 1, isRequired: true, requiresPhoto: true, minimumPhotos: 2 },
  { id: "tpl-pos-obra-2", templateId: "tpl-pos-obra", title: "Fotografar ambientes antes do servico", description: "Registrar fotos panoramicas por ambiente.", sortOrder: 2, isRequired: true, requiresPhoto: true, minimumPhotos: 3 },
  { id: "tpl-pos-obra-3", templateId: "tpl-pos-obra", title: "Proteger superficies sensiveis", description: "Proteger metais, pedras especiais e marcenaria.", sortOrder: 3, isRequired: true, requiresPhoto: true, minimumPhotos: 1 },
  { id: "tpl-pos-obra-4", templateId: "tpl-pos-obra", title: "Remover residuos grossos", description: "Retirar sobras de obra antes da limpeza fina.", sortOrder: 4, isRequired: true, requiresPhoto: false, minimumPhotos: 0 },
  { id: "tpl-pos-obra-5", templateId: "tpl-pos-obra", title: "Aspirar po fino", description: "Aspirar pisos, cantos e rodapes.", sortOrder: 5, isRequired: true, requiresPhoto: false, minimumPhotos: 0 },
  { id: "tpl-pos-obra-6", templateId: "tpl-pos-obra", title: "Limpar pisos", description: "Limpeza mecanizada ou manual conforme superficie.", sortOrder: 6, isRequired: true, requiresPhoto: false, minimumPhotos: 0 },
  { id: "tpl-pos-obra-7", templateId: "tpl-pos-obra", title: "Limpar rejuntes", description: "Remover residuos e manchas superficiais.", sortOrder: 7, isRequired: true, requiresPhoto: false, minimumPhotos: 0 },
  { id: "tpl-pos-obra-8", templateId: "tpl-pos-obra", title: "Limpar vidros e esquadrias", description: "Finalizar vidros sem marcas.", sortOrder: 8, isRequired: true, requiresPhoto: false, minimumPhotos: 0 },
  { id: "tpl-pos-obra-9", templateId: "tpl-pos-obra", title: "Fazer revisao final", description: "Conferencia com supervisor antes da entrega.", sortOrder: 9, isRequired: true, requiresPhoto: true, minimumPhotos: 1 },
  { id: "tpl-pos-obra-10", templateId: "tpl-pos-obra", title: "Fotografar resultado final", description: "Registrar evidencias para garantia e pos-venda.", sortOrder: 10, isRequired: true, requiresPhoto: true, minimumPhotos: 3 },
  { id: "tpl-marmore-1", templateId: "tpl-marmore", title: "Avaliar tipo de pedra", description: "Identificar marmore, sensibilidade e riscos.", sortOrder: 1, isRequired: true, requiresPhoto: false, minimumPhotos: 0 },
  { id: "tpl-marmore-2", templateId: "tpl-marmore", title: "Fotografar danos", description: "Registrar riscos, manchas e trincas.", sortOrder: 2, isRequired: true, requiresPhoto: true, minimumPhotos: 2 },
  { id: "tpl-marmore-3", templateId: "tpl-marmore", title: "Proteger areas adjacentes", description: "Proteger rodapes e mobiliario.", sortOrder: 3, isRequired: true, requiresPhoto: true, minimumPhotos: 1 },
  { id: "tpl-marmore-4", templateId: "tpl-marmore", title: "Realizar teste localizado", description: "Validar abrasivo e produto em area controlada.", sortOrder: 4, isRequired: true, requiresPhoto: true, minimumPhotos: 1 },
  { id: "tpl-marmore-5", templateId: "tpl-marmore", title: "Fazer lixamento inicial", description: "Remover riscos profundos conforme avaliacao.", sortOrder: 5, isRequired: true, requiresPhoto: false, minimumPhotos: 0 },
  { id: "tpl-marmore-6", templateId: "tpl-marmore", title: "Fazer lixamento intermediario", description: "Uniformizar superficie.", sortOrder: 6, isRequired: true, requiresPhoto: false, minimumPhotos: 0 },
  { id: "tpl-marmore-7", templateId: "tpl-marmore", title: "Fazer acabamento fino", description: "Preparar brilho final.", sortOrder: 7, isRequired: true, requiresPhoto: false, minimumPhotos: 0 },
  { id: "tpl-marmore-8", templateId: "tpl-marmore", title: "Realizar polimento", description: "Polimento progressivo conforme superficie.", sortOrder: 8, isRequired: true, requiresPhoto: true, minimumPhotos: 1 },
  { id: "tpl-marmore-9", templateId: "tpl-marmore", title: "Aplicar protecao", description: "Aplicar protetor conforme contrato.", sortOrder: 9, isRequired: true, requiresPhoto: false, minimumPhotos: 0 },
  { id: "tpl-marmore-10", templateId: "tpl-marmore", title: "Realizar inspecao final", description: "Validar brilho, cantos e aceite.", sortOrder: 10, isRequired: true, requiresPhoto: true, minimumPhotos: 2 },
  { id: "tpl-granito-1", templateId: "tpl-granito", title: "Teste localizado", description: "Testar abrasivo e acabamento.", sortOrder: 1, isRequired: true, requiresPhoto: true, minimumPhotos: 1 },
  { id: "tpl-granito-2", templateId: "tpl-granito", title: "Lixamento e nivelamento", description: "Corrigir riscos e desniveis leves.", sortOrder: 2, isRequired: true, requiresPhoto: false, minimumPhotos: 0 },
  { id: "tpl-granito-3", templateId: "tpl-granito", title: "Polimento final", description: "Finalizar brilho uniforme.", sortOrder: 3, isRequired: true, requiresPhoto: true, minimumPhotos: 2 },
  { id: "tpl-impermeabilizacao-1", templateId: "tpl-impermeabilizacao", title: "Preparar superficie", description: "Limpar e secar area antes da aplicacao.", sortOrder: 1, isRequired: true, requiresPhoto: true, minimumPhotos: 1 },
  { id: "tpl-impermeabilizacao-2", templateId: "tpl-impermeabilizacao", title: "Aplicar impermeabilizante", description: "Aplicar conforme especificacao tecnica.", sortOrder: 2, isRequired: true, requiresPhoto: true, minimumPhotos: 1 },
  { id: "tpl-manchas-1", templateId: "tpl-manchas", title: "Diagnosticar mancha", description: "Identificar origem provavel da mancha.", sortOrder: 1, isRequired: true, requiresPhoto: true, minimumPhotos: 1 },
  { id: "tpl-manchas-2", templateId: "tpl-manchas", title: "Aplicar tratamento controlado", description: "Remover mancha com teste progressivo.", sortOrder: 2, isRequired: true, requiresPhoto: true, minimumPhotos: 1 },
  { id: "tpl-porcelanato-1", templateId: "tpl-porcelanato", title: "Limpar rejuntes", description: "Remover residuos e manchas de rejunte.", sortOrder: 1, isRequired: true, requiresPhoto: false, minimumPhotos: 0 },
  { id: "tpl-porcelanato-2", templateId: "tpl-porcelanato", title: "Revisar acabamento", description: "Conferir marcas, manchas e brilho.", sortOrder: 2, isRequired: true, requiresPhoto: true, minimumPhotos: 1 },
];

export const evaluations: Evaluation[] = [
  {
    id: "eval-001",
    serviceOrderId: "os-2403",
    employeeId: "emp-joao",
    employeeName: "Joao Pereira",
    supervisorUserId: "usr-supervisor",
    supervisorName: "Supervisor",
    punctualityScore: 5,
    qualityScore: 5,
    productivityScore: 4,
    careScore: 5,
    teamworkScore: 5,
    clientPostureScore: 5,
    checklistComplianceScore: 5,
    overallScore: 4.9,
    positiveNotes: "Entrega com brilho uniforme, bordas bem acabadas e excelente cuidado com o balcao.",
    improvementNotes: "Enviar mais fotos intermediarias para o relatorio do cliente.",
    seriousIssue: false,
    needsTraining: false,
    createdAt: "2026-06-26",
  },
  {
    id: "eval-002",
    serviceOrderId: "os-2403",
    employeeId: "emp-marina",
    employeeName: "Marina Lopes",
    supervisorUserId: "usr-supervisor",
    supervisorName: "Supervisor",
    punctualityScore: 5,
    qualityScore: 4,
    productivityScore: 5,
    careScore: 5,
    teamworkScore: 5,
    clientPostureScore: 4,
    checklistComplianceScore: 5,
    overallScore: 4.7,
    positiveNotes: "Checklist completo e organizacao exemplar da area antes da reabertura da recepcao.",
    improvementNotes: "Revisar tecnica de remocao de manchas em cantos e areas estreitas.",
    seriousIssue: false,
    needsTraining: false,
    createdAt: "2026-06-26",
  },
  {
    id: "eval-003",
    serviceOrderId: "os-2403",
    employeeId: "emp-carlos",
    employeeName: "Carlos Nunes",
    supervisorUserId: "usr-gerente",
    supervisorName: "Gerente",
    punctualityScore: 5,
    qualityScore: 5,
    productivityScore: 5,
    careScore: 5,
    teamworkScore: 5,
    clientPostureScore: 5,
    checklistComplianceScore: 4,
    overallScore: 4.9,
    positiveNotes: "Coordenou a janela noturna sem atrasar a liberacao do hotel.",
    improvementNotes: "Padronizar a delegacao de fotos para reduzir dependencia do supervisor.",
    seriousIssue: false,
    needsTraining: false,
    createdAt: "2026-06-26",
  },
  {
    id: "eval-004",
    serviceOrderId: "os-2404",
    employeeId: "emp-diego",
    employeeName: "Diego Ramos",
    supervisorUserId: "usr-supervisor",
    supervisorName: "Supervisor",
    punctualityScore: 3,
    qualityScore: 4,
    productivityScore: 3,
    careScore: 4,
    teamworkScore: 4,
    clientPostureScore: 3,
    checklistComplianceScore: 3,
    overallScore: 3.4,
    positiveNotes: "Boa evolucao tecnica quando recebe orientacao direta.",
    improvementNotes: "Precisa cumprir checklist sem lembrete e melhorar comunicacao com cliente.",
    seriousIssue: false,
    needsTraining: true,
    createdAt: "2026-06-12",
  },
  {
    id: "eval-005",
    serviceOrderId: "os-2401",
    employeeId: "emp-rafael",
    employeeName: "Rafael Costa",
    supervisorUserId: "usr-gerente",
    supervisorName: "Gerente",
    punctualityScore: 5,
    qualityScore: 5,
    productivityScore: 4,
    careScore: 5,
    teamworkScore: 4,
    clientPostureScore: 5,
    checklistComplianceScore: 5,
    overallScore: 4.8,
    positiveNotes: "Excelente regularidade no acabamento e baixo retrabalho em granito escuro.",
    improvementNotes: "Antecipar lista de insumos antes do deslocamento para obra.",
    seriousIssue: false,
    needsTraining: false,
    createdAt: "2026-06-30",
  },
  {
    id: "eval-006",
    serviceOrderId: "os-2406",
    employeeId: "emp-bianca",
    employeeName: "Bianca Alves",
    supervisorUserId: "usr-supervisor",
    supervisorName: "Supervisor",
    punctualityScore: 4,
    qualityScore: 5,
    productivityScore: 4,
    careScore: 5,
    teamworkScore: 4,
    clientPostureScore: 4,
    checklistComplianceScore: 5,
    overallScore: 4.4,
    positiveNotes: "Aplicacao controlada e excelente protecao dos ambientes.",
    improvementNotes: "Melhorar previsibilidade de prazo em areas extensas.",
    seriousIssue: false,
    needsTraining: false,
    createdAt: "2026-05-21",
  },
];

export const materials: Material[] = [
  { id: "mat-001", name: "Disco diamantado 400", unit: "un", status: "LOW_STOCK", currentStock: 4, minStock: 5, unitCost: 54 },
  { id: "mat-002", name: "Cristalizador para marmore", unit: "L", status: "AVAILABLE", currentStock: 12, minStock: 8, unitCost: 72 },
  { id: "mat-003", name: "Removedor pos-obra alcalino", unit: "L", status: "LOW_STOCK", currentStock: 3, minStock: 10, unitCost: 38 },
  { id: "mat-004", name: "Manta de protecao", unit: "m2", status: "AVAILABLE", currentStock: 75, minStock: 40, unitCost: 9 },
  { id: "mat-005", name: "Selador premium para limestone", unit: "L", status: "LOW_STOCK", currentStock: 2, minStock: 6, unitCost: 118 },
  { id: "mat-006", name: "Fibra branca para acabamento", unit: "un", status: "AVAILABLE", currentStock: 22, minStock: 15, unitCost: 16 },
];

export const equipment: Equipment[] = [
  { id: "eq-001", name: "Politriz industrial", code: "POL-01", status: "RESERVED", notes: "Alocada na OS-2401" },
  { id: "eq-002", name: "Aspirador extrator", code: "ASP-04", status: "AVAILABLE", notes: "Revisado em junho" },
  { id: "eq-003", name: "Lavadora de piso", code: "LAV-02", status: "IN_MAINTENANCE", notes: "Troca de escovas" },
  { id: "eq-004", name: "Politriz orbital compacta", code: "ORB-03", status: "RESERVED", notes: "Alocada na Penthouse Belvedere" },
];

export const serviceOrderMaterials: ServiceOrderMaterial[] = [
  { id: "som-2401-1", serviceOrderId: "os-2401", materialId: "mat-001", plannedQuantity: 6, separatedQuantity: 6, deliveredQuantity: 6, returnedQuantity: 0, consumedQuantity: 2, damagedQuantity: 0, lostQuantity: 0, status: "DELIVERED_TO_TEAM", notes: "Discos entregues para etapa de desbaste.", preparedByUserId: "usr-almoxarifado", deliveredByUserId: "usr-almoxarifado", createdAt: "2026-07-01T15:00:00", updatedAt: "2026-07-02T07:30:00" },
  { id: "som-2401-2", serviceOrderId: "os-2401", materialId: "mat-002", plannedQuantity: 8, separatedQuantity: 8, deliveredQuantity: 8, returnedQuantity: 0, consumedQuantity: 0, damagedQuantity: 0, lostQuantity: 0, status: "DELIVERED_TO_TEAM", notes: "Cristalizador reservado para etapa final.", preparedByUserId: "usr-almoxarifado", deliveredByUserId: "usr-almoxarifado", createdAt: "2026-07-01T15:00:00", updatedAt: "2026-07-02T07:30:00" },
  { id: "som-2402-1", serviceOrderId: "os-2402", materialId: "mat-003", plannedQuantity: 5, separatedQuantity: 0, deliveredQuantity: 0, returnedQuantity: 0, consumedQuantity: 0, damagedQuantity: 0, lostQuantity: 0, status: "PENDING_SEPARATION", notes: "Separar removedor para limpeza pos-obra.", createdAt: "2026-07-01T10:30:00", updatedAt: "2026-07-01T10:30:00" },
  { id: "som-2402-2", serviceOrderId: "os-2402", materialId: "mat-004", plannedQuantity: 30, separatedQuantity: 20, deliveredQuantity: 0, returnedQuantity: 0, consumedQuantity: 0, damagedQuantity: 0, lostQuantity: 0, status: "SEPARATING", notes: "Completar manta antes da saida da equipe.", preparedByUserId: "usr-almoxarifado", createdAt: "2026-07-01T10:30:00", updatedAt: "2026-07-02T08:00:00" },
  { id: "som-2406-1", serviceOrderId: "os-2406", materialId: "mat-005", plannedQuantity: 6, separatedQuantity: 2, deliveredQuantity: 0, returnedQuantity: 0, consumedQuantity: 0, damagedQuantity: 0, lostQuantity: 0, status: "SEPARATING", notes: "Estoque abaixo do planejado; compras precisa repor.", preparedByUserId: "usr-almoxarifado", createdAt: "2026-07-01T17:30:00", updatedAt: "2026-07-02T09:15:00" },
];

export const serviceOrderEquipment: ServiceOrderEquipment[] = [
  { id: "soequip-2401-1", serviceOrderId: "os-2401", equipmentId: "eq-001", status: "IN_USE", reservedAt: "2026-07-01T15:00:00", deliveredAt: "2026-07-02T07:30:00", deliveredByUserId: "usr-almoxarifado", conditionBefore: "Revisada, disco novo instalado", notes: "Retorno previsto em 05/07.", createdAt: "2026-07-01T15:00:00", updatedAt: "2026-07-02T07:30:00" },
  { id: "soequip-2404-1", serviceOrderId: "os-2404", equipmentId: "eq-004", status: "IN_USE", reservedAt: "2026-06-29T16:30:00", deliveredAt: "2026-06-30T07:40:00", deliveredByUserId: "usr-almoxarifado", conditionBefore: "Normal", notes: "Atraso na devolucao por bloqueio de elevador.", createdAt: "2026-06-29T16:30:00", updatedAt: "2026-07-02T08:00:00" },
  { id: "soequip-2402-1", serviceOrderId: "os-2402", equipmentId: "eq-002", status: "RESERVED", reservedAt: "2026-07-03T15:00:00", conditionBefore: "Disponivel e revisado", notes: "Entregar na manha da limpeza.", createdAt: "2026-07-01T10:30:00", updatedAt: "2026-07-01T10:30:00" },
];

export const materialRequests: ServiceMaterialRequest[] = [
  { id: "req-2404-1", serviceOrderId: "os-2404", requestedByUserId: "usr-supervisor", status: "PENDING", priority: "URGENT", reason: "Necessario mais fibra branca para finalizar cristalizacao apos extensao de area.", createdAt: "2026-07-02T09:40:00", updatedAt: "2026-07-02T09:40:00" },
];

export const materialRequestItems: ServiceMaterialRequestItem[] = [
  { id: "reqitem-2404-1", requestId: "req-2404-1", materialId: "mat-006", quantity: 8, notes: "Entregar ainda hoje na Penthouse Belvedere." },
];

export const supervisorEvaluations: SupervisorEvaluation[] = [
  { id: "seval-001", serviceOrderId: "os-2403", supervisorEmployeeId: "emp-carlos", supervisorUserId: "usr-supervisor", employeeId: "emp-marina", employeeUserId: "usr-colaborador-marina", clarityScore: 5, organizationScore: 5, respectScore: 5, taskDistributionScore: 4, communicationScore: 5, supportScore: 5, leadershipScore: 5, overallScore: 4.9, positiveNotes: "Orientacao clara e apoio durante a janela noturna.", improvementNotes: "Distribuir fotos durante a execucao para nao acumular no final.", createdAt: "2026-06-26T08:00:00", updatedAt: "2026-06-26T08:00:00" },
  { id: "seval-002", serviceOrderId: "os-2405", supervisorEmployeeId: "emp-luciana", supervisorUserId: "usr-supervisor-2", employeeId: "emp-rafael", employeeUserId: "usr-colaborador-rafael", clarityScore: 5, organizationScore: 5, respectScore: 5, taskDistributionScore: 5, communicationScore: 4, supportScore: 5, leadershipScore: 5, overallScore: 4.9, positiveNotes: "Checklist organizado e materiais conferidos antes da saida.", improvementNotes: "Avisar mudanca de horario com mais antecedencia.", createdAt: "2026-06-30T18:00:00", updatedAt: "2026-06-30T18:00:00" },
];

export const scheduleEvents: ScheduleEvent[] = [
  { id: "sch-001", title: "Execucao OS-2401", description: "Polimento e cristalizacao no Condominio Aurora Jardins.", type: "SERVICE_ORDER", serviceOrderId: "os-2401", assignedUserId: "usr-supervisor", assignedEmployeeId: "emp-carlos", startsAt: "2026-07-02T08:00:00", endsAt: "2026-07-05T18:00:00", status: "IN_PROGRESS", priority: "HIGH", createdAt: "2026-07-01T14:00:00", updatedAt: "2026-07-02T08:00:00" },
  { id: "sch-002", title: "Separar materiais OS-2402", description: "Removedor, manta e aspirador para limpeza pos-obra.", type: "MATERIAL_PREPARATION", serviceOrderId: "os-2402", assignedUserId: "usr-almoxarifado", startsAt: "2026-07-03T15:00:00", endsAt: "2026-07-03T16:00:00", status: "SCHEDULED", priority: "NORMAL", createdAt: "2026-07-01T10:30:00", updatedAt: "2026-07-01T10:30:00" },
  { id: "sch-003", title: "Retorno politriz orbital", description: "Equipamento da Penthouse Belvedere com retorno pendente.", type: "EQUIPMENT_RETURN", serviceOrderId: "os-2404", assignedUserId: "usr-almoxarifado", startsAt: "2026-07-02T17:00:00", endsAt: "2026-07-02T18:00:00", status: "DELAYED", priority: "URGENT", createdAt: "2026-07-02T08:00:00", updatedAt: "2026-07-02T08:00:00" },
  { id: "sch-004", title: "Vistoria Casa Alto Jardim", description: "Avaliar manchas em limestone claro.", type: "INSPECTION", inspectionId: "ins-004", assignedUserId: "usr-gerente", startsAt: "2026-07-03T10:00:00", endsAt: "2026-07-03T11:30:00", status: "SCHEDULED", priority: "NORMAL", createdAt: "2026-07-01T09:00:00", updatedAt: "2026-07-01T09:00:00" },
  { id: "sch-005", title: "Pos-venda Hotel Serra Azul", description: "Confirmar satisfacao e oferecer manutencao trimestral.", type: "AFTER_SALES", serviceOrderId: "os-2403", assignedUserId: "usr-comercial", startsAt: "2026-07-04T09:00:00", endsAt: "2026-07-04T09:30:00", status: "SCHEDULED", priority: "LOW", createdAt: "2026-06-26T09:00:00", updatedAt: "2026-06-26T09:00:00" },
];

export const auditLogs: AuditLog[] = [
  { id: "audit-001", userId: "usr-gerente", action: "ASSIGN_SUPERVISOR", entity: "ServiceOrder", entityId: "os-2401", newValueJson: { supervisorUserId: "usr-supervisor", supervisorEmployeeId: "emp-carlos" }, createdAt: "2026-07-01T14:00:00" },
  { id: "audit-002", userId: "usr-supervisor", action: "COMPLETE_CHECKLIST_ITEM", entity: "ServiceOrderChecklistItem", entityId: "chk-2401-1", newValueJson: { completedByEmployeeId: "emp-ines" }, createdAt: "2026-07-02T09:10:00" },
  { id: "audit-003", userId: "usr-supervisor", action: "REQUEST_EXTRA_MATERIAL", entity: "ServiceMaterialRequest", entityId: "req-2404-1", newValueJson: { priority: "URGENT" }, createdAt: "2026-07-02T09:40:00" },
];

export const dashboardMetrics: DashboardMetric[] = [
  { label: "Leads novos", value: "2", trend: "R$ 67,8 mil em potencial", tone: "primary" },
  { label: "Orcamentos pendentes", value: "3", trend: "R$ 139,7 mil em aberto", tone: "warning" },
  { label: "OS em execucao", value: "3", trend: "1 obra atrasada exige acao", tone: "info" },
  { label: "Obras sem avaliacao", value: "1", trend: "Fechar avaliacao da OS-2405", tone: "error" },
  { label: "Media da equipe", value: "4,5", trend: "2 colaboradores em destaque", tone: "success" },
  { label: "Receita estimada do mes", value: "R$ 202,9 mil", trend: "Julho em andamento", tone: "success" },
  { label: "Servicos finalizados", value: "2", trend: "1 pendente de avaliacao", tone: "primary" },
  { label: "Colaboradores ativos", value: "6", trend: "2 precisam de treinamento", tone: "warning" },
];

export const revenueByMonth: ChartPoint[] = [
  { label: "Jan", value: 112 },
  { label: "Fev", value: 128 },
  { label: "Mar", value: 141 },
  { label: "Abr", value: 167 },
  { label: "Mai", value: 192 },
  { label: "Jun", value: 214 },
  { label: "Jul", value: 203 },
];

export const servicesByStatus: ChartPoint[] = [
  { label: "Agendado", value: 1 },
  { label: "Preparando", value: 1 },
  { label: "Execucao", value: 2 },
  { label: "Finalizado", value: 2 },
];

export const averageRatings: ChartPoint[] = [
  { label: "Pontualidade", value: 4.5 },
  { label: "Qualidade tecnica", value: 4.6 },
  { label: "Produtividade", value: 4.2 },
  { label: "Checklist", value: 4.5 },
];

export const mostExecutedServices: ChartPoint[] = [
  { label: "Limpeza pos-obra", value: 36 },
  { label: "Polimento de granito", value: 31 },
  { label: "Restauracao de marmore", value: 19 },
  { label: "Impermeabilizacao", value: 14 },
];

const cleanSimulationOwner = users.find((user) => user.role === "OWNER") ?? {
  id: "usr-owner",
  name: "Dono",
  email: "dono@empresa.com",
  role: "OWNER" as const,
  isActive: true,
};

users.splice(0, users.length, cleanSimulationOwner);
customers.length = 0;
leads.length = 0;
inspections.length = 0;
quotes.length = 0;
employees.length = 0;
serviceOrders.length = 0;
serviceOrderEmployees.length = 0;
serviceOrderChecklistItems.length = 0;
serviceOrderChecklistPhotos.length = 0;
serviceOrderChecklistEvents.length = 0;
serviceOrderMaterials.length = 0;
serviceOrderEquipment.length = 0;
materials.length = 0;
equipment.length = 0;
materialRequests.length = 0;
materialRequestItems.length = 0;
evaluations.length = 0;
supervisorEvaluations.length = 0;
scheduleEvents.length = 0;
auditLogs.length = 0;
dashboardMetrics.length = 0;
revenueByMonth.length = 0;
servicesByStatus.length = 0;
averageRatings.length = 0;
mostExecutedServices.length = 0;
